// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOE8ZLTnGvNeeUp_X7jZiJmKe1xYLDg24',
    appId: '1:288285219930:web:b9f1e8cfa64f4c12f4cc63',
    messagingSenderId: '288285219930',
    projectId: 'e-commerce-fruit-app',
    authDomain: 'e-commerce-fruit-app.firebaseapp.com',
    storageBucket: 'e-commerce-fruit-app.firebasestorage.app',
    measurementId: 'G-LS5LKCT0KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC343tU1_n-n6pOZKKNb83CwwImlsnVSwo',
    appId: '1:288285219930:android:abb7087949357d38f4cc63',
    messagingSenderId: '288285219930',
    projectId: 'e-commerce-fruit-app',
    storageBucket: 'e-commerce-fruit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbmQWiX-6BD1MKvv7jav3xAfjVtGNixAM',
    appId: '1:288285219930:ios:458ff47dbb9247eff4cc63',
    messagingSenderId: '288285219930',
    projectId: 'e-commerce-fruit-app',
    storageBucket: 'e-commerce-fruit-app.firebasestorage.app',
    androidClientId: '288285219930-9u4dnhu4vuncek0vsduug75ckqbkbr62.apps.googleusercontent.com',
    iosClientId: '288285219930-t1ts50u1h2jadd03tklleca51i5obroa.apps.googleusercontent.com',
    iosBundleId: 'com.example.productDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbmQWiX-6BD1MKvv7jav3xAfjVtGNixAM',
    appId: '1:288285219930:ios:458ff47dbb9247eff4cc63',
    messagingSenderId: '288285219930',
    projectId: 'e-commerce-fruit-app',
    storageBucket: 'e-commerce-fruit-app.firebasestorage.app',
    androidClientId: '288285219930-9u4dnhu4vuncek0vsduug75ckqbkbr62.apps.googleusercontent.com',
    iosClientId: '288285219930-t1ts50u1h2jadd03tklleca51i5obroa.apps.googleusercontent.com',
    iosBundleId: 'com.example.productDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOE8ZLTnGvNeeUp_X7jZiJmKe1xYLDg24',
    appId: '1:288285219930:web:ffe7ace5c65ff804f4cc63',
    messagingSenderId: '288285219930',
    projectId: 'e-commerce-fruit-app',
    authDomain: 'e-commerce-fruit-app.firebaseapp.com',
    storageBucket: 'e-commerce-fruit-app.firebasestorage.app',
    measurementId: 'G-DB4PPWL8MM',
  );
}
